container:
  dockerfile: Dockerfile
  cpu: 6
  memory: 12G
  use_in_memory_disk: true
task:
  build_script:
  - git clone --depth=1 https://github.com/Stealth1226/msm8996_lge_kernel -b mk2k-4.4
  - cd msm8996_lge_kernel
  - git clone https://github.com/kdrag0n/proton-clang --depth=1 
  - export PATH="$(pwd)/proton-clang/bin:$PATH"
  - export ARCH=arm64 && SUBARCH=arm64
  - make lineageos_rs988_defconfig
  - make CC=clang CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc --all)
  - curl --upload-file arch/arm64/boot/*dtb https://transfer.sh/$(basename arch/arm64/boot/*dtb)
