container:
  dockerfile: Dockerfile
  cpu: 2
  memory: 4G
  use_in_memory_disk: true
task:
  build_script:
  - tmate -S /tmp/tmate.sock new-session -d && tmate -S /tmp/tmate.sock wait tmate-ready && send_shell=$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}') && echo "$send_shell" && sleep 2h


