env:
    GH-TOKEN: "ENCRYPTED[302a3e6d5ebf39ed7baa069852e86218893ebd28a9e5d39624c53d5f72b19721fc7357172890d0ec0486a9f863a82338]"

task:
  name: "build"
  timeout_in: 120m  
  container:
      dockerfile: Dockerfile
      cpu: 4
      memory: 4G

  Sync_script:
      - echo "https://Stealth1226:$GH-TOKEN@github.com" > ~/.git-credentials
      - git config --global credential.helper store
      - mkdir -p ~/lighthouse
      - cd ~/lighthouse
      - repo init --depth=1 -u git://github.com/lighthouse-os/manifest.git -b sailboat -g default,-mips,-darwin,-notdefault
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8 || true

  Merge_script:
      - cd ~/lighthouse
      - wget https://raw.githubusercontent.com/Stealth1226/ci/merger/merge-aosp.sh
      - bash merge-aosp.sh r16 
      - tmate -S /tmp/tmate.sock new-session -d && tmate -S /tmp/tmate.sock wait tmate-ready && tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}' && sleep 2h
