container:
  dockerfile: Dockerfile
  cpu: 6
  memory: 12G
  use_in_memory_disk: true
task:
  build_script:
  - git clone --depth=1 https://github.com/Stealth1226/android_kernel_lge_msm8996 -b mk2000-custom
  - cd android_kernel_lge_msm8996
  - git clone https://github.com/mvaisakh/gcc-arm --depth=1 
  - git clone https://github.com/mvaisakh/gcc-arm64 --depth=1 
  - ./build.sh RS988
  - curl --upload-file out/*zip https://transfer.sh/$(basename out/*zip)
