container:
  dockerfile: Dockerfile
  cpu: 6
  memory: 10G
  use_in_memory_disk: true
task:
  build_script:
  - git clone --depth=1 https://github.com/Stealth1226/kernel_xiaomi_sm6250
  - cd kernel_xiaomi_sm6250
  - mkdir out
  - git clone https://github.com/kdrag0n/proton-clang --depth=1 
  - export ARCH=arm64 && SUBARCH=arm64 && export PATH="$(pwd)/proton-clang/bin:$PATH" && make O=out cust_defconfig && make -j$(nproc --all) O=out CC=clang CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- 
  - curl -T out/arch/arm64/boot/Image.gz-dtb temp.sh; echo
  - curl -T out/arch/arm64/boot/dtbo.img temp.sh; echo
 
